// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, created_at, updated_at, name, type, amount, due_date, bank, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, updated_at, name, type, amount, due_date, bank, user_id
`

type CreateTransactionParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Type      string
	Amount    float64
	DueDate   int32
	Bank      string
	UserID    uuid.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Type,
		arg.Amount,
		arg.DueDate,
		arg.Bank,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Type,
		&i.Amount,
		&i.DueDate,
		&i.Bank,
		&i.UserID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getTransactionByName = `-- name: GetTransactionByName :one
SELECT id, created_at, updated_at, name, type, amount, due_date, bank, user_id FROM transactions
WHERE name = $1
`

func (q *Queries) GetTransactionByName(ctx context.Context, name string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByName, name)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Type,
		&i.Amount,
		&i.DueDate,
		&i.Bank,
		&i.UserID,
	)
	return i, err
}
