// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, created_at, updated_at, t_name, t_type, amount, due_date, bank, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, updated_at, t_name, t_type, amount, due_date, bank, user_id
`

type CreateTransactionParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	TName     string
	TType     string
	Amount    float64
	DueDate   int32
	Bank      string
	UserID    uuid.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TName,
		arg.TType,
		arg.Amount,
		arg.DueDate,
		arg.Bank,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TName,
		&i.TType,
		&i.Amount,
		&i.DueDate,
		&i.Bank,
		&i.UserID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const editTransaction = `-- name: EditTransaction :one
UPDATE transactions
SET updated_at = $2, t_name = $3, t_type = $4, amount = $5, due_date = $6, bank = $7
WHERE t_name = $1
RETURNING id, created_at, updated_at, t_name, t_type, amount, due_date, bank, user_id
`

type EditTransactionParams struct {
	TName     string
	UpdatedAt time.Time
	TName_2   string
	TType     string
	Amount    float64
	DueDate   int32
	Bank      string
}

func (q *Queries) EditTransaction(ctx context.Context, arg EditTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, editTransaction,
		arg.TName,
		arg.UpdatedAt,
		arg.TName_2,
		arg.TType,
		arg.Amount,
		arg.DueDate,
		arg.Bank,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TName,
		&i.TType,
		&i.Amount,
		&i.DueDate,
		&i.Bank,
		&i.UserID,
	)
	return i, err
}

const getAllBanks = `-- name: GetAllBanks :many
SELECT DISTINCT bank FROM transactions
`

func (q *Queries) GetAllBanks(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bank string
		if err := rows.Scan(&bank); err != nil {
			return nil, err
		}
		items = append(items, bank)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInTransactionsForUser = `-- name: GetInTransactionsForUser :many
SELECT id, created_at, updated_at, t_name, t_type, amount, due_date, bank, user_id FROM transactions
Where user_id = $1
AND t_type = 'in'
ORDER BY due_date, t_name
`

func (q *Queries) GetInTransactionsForUser(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getInTransactionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TName,
			&i.TType,
			&i.Amount,
			&i.DueDate,
			&i.Bank,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutTransactionsForUser = `-- name: GetOutTransactionsForUser :many
SELECT id, created_at, updated_at, t_name, t_type, amount, due_date, bank, user_id FROM transactions
Where user_id = $1
AND t_type = 'out'
ORDER BY due_date, t_name
`

func (q *Queries) GetOutTransactionsForUser(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getOutTransactionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TName,
			&i.TType,
			&i.Amount,
			&i.DueDate,
			&i.Bank,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByName = `-- name: GetTransactionByName :one
SELECT id, created_at, updated_at, t_name, t_type, amount, due_date, bank, user_id FROM transactions
WHERE t_name = $1
`

func (q *Queries) GetTransactionByName(ctx context.Context, tName string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByName, tName)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TName,
		&i.TType,
		&i.Amount,
		&i.DueDate,
		&i.Bank,
		&i.UserID,
	)
	return i, err
}

const getTransactionsForUser = `-- name: GetTransactionsForUser :many
SELECT id, created_at, updated_at, t_name, t_type, amount, due_date, bank, user_id FROM transactions
Where user_id = $1
`

func (q *Queries) GetTransactionsForUser(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TName,
			&i.TType,
			&i.Amount,
			&i.DueDate,
			&i.Bank,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
